<?php
defined( 'ABSPATH' ) || exit;

Redux::set_section( // General colors
	$opt_name,
	array(
		'title'			=> esc_html__( 'General colors', 'drplus' ),
		'id'			=> 'colors-general-section',
		'subsection'	=> true,
		'fields'		=> array(
			[
				'id'			=> 'body_color',
				'type'			=> 'color',
				'title'			=> __( 'Body color', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#ffffff' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#ffffff',
			],
			[
				'id'			=> 'body_color_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Body color', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#0F1115' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#0F1115',
			],
			[
				'id'			=> 'general_bg_color',
				'type'			=> 'color',
				'title'			=> __( 'General Background color', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#ffffff' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#ffffff',
			],
			[
				'id'			=> 'general_bg_color_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'General Background', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#0F1115' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#0F1115',
			],
			[
				'id'			=> 'text_main_color',
				'type'			=> 'color',
				'title'			=> __( 'Default text color', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#383838' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#383838',
			],
			[
				'id'			=> 'text_main_color_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Default text color', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#F1F1F1' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#F1F1F1',
			],
			[
				'id'			=> 'general_text_color',
				'type'			=> 'color',
				'title'			=> __( 'Light text color', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#ffffff' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#ffffff',
			],
			[
				'id'			=> 'general_text_color_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Dark text color', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#383838' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#383838',
			],
		),
	)
);

Redux::set_section( // Primary colors
	$opt_name,
	array(
		'title'			=> esc_html__( 'Primary colors', 'drplus' ),
		'id'			=> 'colors-primary-section',
		'subsection'	=> true,
		'fields'		=> array(
			[
				'id'			=> 'primary_color_100',
				'type'			=> 'color',
				'title'			=> __( 'Primary', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#1DBAB5' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#1DBAB5',
			],
			[
				'id'			=> 'primary_color_100_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Primary', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#1DBAB5' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#1DBAB5',
			],
			[
				'id'			=> 'primary_color_200',
				'type'			=> 'color',
				'title'			=> __( 'Primary 2', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#159F9B' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#159F9B',
			],
			[
				'id'			=> 'primary_color_200_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Primary 2', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#159F9B' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#159F9B',
			],
		),
	)
);

Redux::set_section( // Secondary colors
	$opt_name,
	array(
		'title'			=> esc_html__( 'Secondary colors', 'drplus' ),
		'id'			=> 'colors-secondary-section',
		'subsection'	=> true,
		'fields'		=> array(
			[
				'id'			=> 'secondary_color_100',
				'type'			=> 'color',
				'title'			=> __( 'Secondary', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#114B5F' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#114B5F',
			],
			[
				'id'			=> 'secondary_color_100_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Secondary', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#177291' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#177291',
			],
			[
				'id'			=> 'secondary_color_200',
				'type'			=> 'color',
				'title'			=> __( 'Secondary 2', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#248cb1' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#248cb1',
			],
			[
				'id'			=> 'secondary_color_200_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Secondary 2', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#0F3E4F' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#0F3E4F',
			],
		),
	)
);

Redux::set_section( // Heading colors
	$opt_name,
	array(
		'title'			=> esc_html__( 'Heading colors', 'drplus' ),
		'id'			=> 'colors-heading-section',
		'subsection'	=> true,
		'fields'		=> array(
			[
				'id'			=> 'heading_color_100',
				'type'			=> 'color',
				'title'			=> __( 'Heading 1', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#373434' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#373434',
			],
			[
				'id'			=> 'heading_color_100_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Heading 1', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#FFFFFF' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#FFFFFF',
			],
			[
				'id'			=> 'heading_color_200',
				'type'			=> 'color',
				'title'			=> __( 'Heading 2', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#181616' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#181616',
			],
			[
				'id'			=> 'heading_color_200_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Heading 2', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#E6E6E6' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#E6E6E6',
			],
		),
	)
);

Redux::set_section( // Gray colors
	$opt_name,
	array(
		'title'			=> esc_html__( 'Gray colors', 'drplus' ),
		'id'			=> 'colors-gray-section',
		'subsection'	=> true,
		'fields'		=> array(
			[ // gray_color_100
				'id'			=> 'gray_color_100',
				'type'			=> 'color',
				'title'			=> __( 'Gray 1', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#F7F7F7' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#F7F7F7',
			],
			[ // gray_color_100_dark
				'id'			=> 'gray_color_100_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Gray 1', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#1C1F23' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#1C1F23',
			],
			[ // gray_color_200
				'id'			=> 'gray_color_200',
				'type'			=> 'color',
				'title'			=> __( 'Gray 2', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#E6E6E6' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#E6E6E6',
			],
			[ // gray_color_200_dark
				'id'			=> 'gray_color_200_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Gray 2', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#22262B' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#22262B',
			],
			[ // gray_color_300
				'id'			=> 'gray_color_300',
				'type'			=> 'color', 
				'title'			=> __( 'Gray 3', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#DBDBDB' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#DBDBDB',
			],
			[ // gray_color_300_dark
				'id'			=> 'gray_color_300_dark',
				'type'			=> 'color', 
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Gray 3', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#2A2F35' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#2A2F35',
			],
			[ // gray_color_400
				'id'			=> 'gray_color_400',
				'type'			=> 'color',
				'title'			=> __( 'Gray 4', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#A7A7A7' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#A7A7A7',
			],
			[ // gray_color_400_dark
				'id'			=> 'gray_color_400_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Gray 4', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#353C45' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#353C45',
			],
		),
	)
);

Redux::set_section( // Text colors
	$opt_name,
	array(
		'title'			=> esc_html__( 'Text colors', 'drplus' ),
		'id'			=> 'colors-text-section',
		'subsection'	=> true,
		'fields'		=> array(
			[
				'id'			=> 'text_color_100',
				'type'			=> 'color',
				'title'			=> __( 'Text 1', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#E7E7E7' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#E7E7E7',
			],
			[
				'id'			=> 'text_color_100_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Text 1', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#F5F5F5' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#F5F5F5',
			],
			[
				'id'			=> 'text_color_200',
				'type'			=> 'color',
				'title'			=> __( 'Text 2', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#A6A6A6' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#A6A6A6',
			],
			[
				'id'			=> 'text_color_200_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Text 2', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#a3a0a0' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#a3a0a0',
			],
			[
				'id'			=> 'text_color_300',
				'type'			=> 'color',
				'title'			=> __( 'Text 3', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#888888' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#888888',
			],
			[
				'id'			=> 'text_color_300_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Text 3', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#CFCFCF' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#CFCFCF',
			],
			[
				'id'			=> 'text_color_400',
				'type'			=> 'color',
				'title'			=> __( 'Text 4', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#848484' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#848484',
			],
			[
				'id'			=> 'text_color_400_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Text 4', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#B8B8B8' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#B8B8B8',
			],
			[
				'id'			=> 'text_color_500',
				'type'			=> 'color',
				'title'			=> __( 'Text 5', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#747474' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#747474',
			],
			[
				'id'			=> 'text_color_500_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Text 5', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#9A9A9A' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#9A9A9A',
			],
			[
				'id'			=> 'text_color_600',
				'type'			=> 'color',
				'title'			=> __( 'Text 6', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#383838' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#383838',
			],
			[
				'id'			=> 'text_color_600_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Text 6', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#b1b1b1' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#b1b1b1',
			],
		),
	)
);

Redux::set_section( // Form colors
	$opt_name,
	array(
		'title'			=> esc_html__( 'Form colors', 'drplus' ),
		'id'			=> 'colors-form-section',
		'subsection'	=> true,
		'fields'		=> array(
			[
				'id'			=> 'input_bg',
				'type'			=> 'color',
				'title'			=> __( 'Input background', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#f5f6f7' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#f5f6f7',
			],
			[
				'id'			=> 'input_bg_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Input background', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#1A1F24' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#1A1F24',
			],
			[
				'id'			=> 'input_secondary_bg',
				'type'			=> 'color',
				'title'			=> __( 'Input secondary background', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#ffffff' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#ffffff',
			],
			[
				'id'			=> 'input_secondary_bg_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Input secondary background', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#12161B' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#12161B',
			],
			[
				'id'			=> 'input_text',
				'type'			=> 'color',
				'title'			=> __( 'Input text color', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#383838' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#383838',
			],
			[
				'id'			=> 'input_text_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Input text color', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#F1F1F1' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#F1F1F1',
			],
		),
	)
);

Redux::set_section( // Widget colors
	$opt_name,
	array(
		'title'			=> esc_html__( 'Widget colors', 'drplus' ),
		'id'			=> 'colors-widget-section',
		'subsection'	=> true,
		'fields'		=> array(
			[
				'id'			=> 'widget_bg',
				'type'			=> 'color',
				'title'			=> __( 'Widget background', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#F7F7F7' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#F7F7F7',
			],
			[
				'id'			=> 'widget_bg_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Widget background', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#091022' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#091022',
			],
			[
				'id'			=> 'widget_title_bg',
				'type'			=> 'color',
				'title'			=> __( 'Widget title background color', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#1dbab5' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#1dbab5',
			],
			[
				'id'			=> 'widget_title_bg_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Widget title background color', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#1dbab5' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#1dbab5',
			],
			[
				'id'			=> 'widget_title',
				'type'			=> 'color',
				'title'			=> __( 'Widget title color', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#ffffff' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#ffffff',
			],
			[
				'id'			=> 'widget_title_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Widget title color', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#ffffff' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#ffffff',
			],
			[
				'id'			=> 'widget_text_color',
				'type'			=> 'color',
				'title'			=> __( 'Widget text color', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#383838' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#383838',
			],
			[
				'id'			=> 'widget_text_color_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Widget text color', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#EDEDED' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#EDEDED',
			],
			[
				'id'			=> 'widget_links_color',
				'type'			=> 'color',
				'title'			=> __( 'Widget links color', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#383838' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#383838',
			],
			[
				'id'			=> 'widget_links_color_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Widget links color', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#EDEDED' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#EDEDED',
			],
		),
	)
);

Redux::set_section( // Other colors
	$opt_name,
	array(
		'title'			=> esc_html__( 'Other colors', 'drplus' ),
		'id'			=> 'colors-other-section',
		'subsection'	=> true,
		'fields'		=> array(
			[
				'id'			=> 'blue',
				'type'			=> 'color',
				'title'			=> __( 'Blue', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#114B5F' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#114B5F',
			],
			[
				'id'			=> 'blue_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Blue', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#114B5F' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#114B5F',
			],
			[
				'id'			=> 'green',
				'type'			=> 'color',
				'title'			=> __( 'Green', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#1dbab5' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#1dbab5',
			],
			[
				'id'			=> 'green_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Green', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#1dbab5' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#1dbab5',
			],
			[
				'id'			=> 'yellow',
				'type'			=> 'color',
				'title'			=> __( 'Yellow', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#FFBD12' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#FFBD12',
			],
			[
				'id'			=> 'yellow_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Yellow', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#FFBD12' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#FFBD12',
			],
			[
				'id'			=> 'red',
				'type'			=> 'color',
				'title'			=> __( 'Red', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#d60043' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#d60043',
			],
			[
				'id'			=> 'red_dark',
				'type'			=> 'color',
				'title'			=> sprintf( __( '%s (Dark mode)', 'drplus' ), __( 'Red', 'drplus' ) ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), '#d60043' ),
				'compiler'		=> true,
				'transparent'	=> false,
				'default'		=> '#d60043',
			],
		),
	)
);
