<?php

defined( 'ABSPATH' ) || exit;

$separator = is_rtl() ? ' &rsaquo; ' : ' &lsaquo; ';

Redux::set_section( // Speciality single settings
	$opt_name,
	array(
		'title'			=> esc_html__( 'Speciality single settings', 'drplus' ),
		'id'			=> 'speciality-single-section',
		'subsection'	=> true,
		'fields'		=> array(
			[ // single_specialty_breadcrumb
				'id'		=> 'single_specialty_breadcrumb',
				'type'		=> 'switch',
				'title'		=> esc_html__( 'Show breadcrumb', 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), esc_html__( 'Enabled', 'drplus' ) ),
				'on'		=> esc_html__( 'Enabled', 'drplus' ),
				'off'		=> esc_html__( 'Disabled', 'drplus' ),
				'default'	=> true,
			],
			[ // single_specialty_show_title
				'id'		=> 'single_specialty_show_title',
				'type'		=> 'switch',
				'title'		=> esc_html__( 'Show title', 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), esc_html__( 'Enabled', 'drplus' ) ),
				'on'		=> esc_html__( 'Enabled', 'drplus' ),
				'off'		=> esc_html__( 'Disabled', 'drplus' ),
				'default'	=> true,
			],
			[ // single_specialty_show_title
				'id'		=> 'single_specialty_show_icon',
				'type'		=> 'switch',
				'title'		=> esc_html__( 'Show icon', 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), esc_html__( 'Enabled', 'drplus' ) ),
				'on'		=> esc_html__( 'Enabled', 'drplus' ),
				'off'		=> esc_html__( 'Disabled', 'drplus' ),
				'default'	=> true,
			],
			[ // single_specialty_show_sidebar
				'id'		=> 'single_specialty_show_sidebar',
				'type'		=> 'switch',
				'title'		=> esc_html__( 'Show sidebar', 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), esc_html__( 'Enabled', 'drplus' ) ),
				'on'		=> esc_html__( 'Enabled', 'drplus' ),
				'off'		=> esc_html__( 'Disabled', 'drplus' ),
				'default'	=> true,
			],
			[ // single_specialty_sidebar
				'id'		=> 'single_specialty_sidebar',
				'type'		=> 'select',
				'title'		=> esc_html__( 'Sidebar', 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), esc_html__( 'Single speciality sidebar', 'drplus' ) ),
				'data'		=> 'sidebars',
				'default'	=> 'single_speciality',
				'required'	=> [
					['single_specialty_show_sidebar','=',true],
				]
			],
			[ // single_specialty_desktop_cols
				'id'		=> 'single_specialty_desktop_cols',
				'type'		=> 'spinner',
				'title'		=> esc_html__( "Desktop columns", 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), '4' ),
				'min'		=> 1,
				'max'		=> 6,
				'default'	=> 4,
			],
			[ // single_specialty_desktop_gap
				'id'		=> 'single_specialty_desktop_gap',
				'type'		=> 'spinner',
				'title'		=> esc_html__( "Desktop gap (px)", 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), '24' ),
				'min'		=> 1,
				'max'		=> 64,
				'default'	=> 16,
			],
			[ // single_specialty_tablet_cols
				'id'		=> 'single_specialty_tablet_cols',
				'type'		=> 'spinner',
				'title'		=> esc_html__( "Tablet columns", 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), '2' ),
				'min'		=> 1,
				'max'		=> 6,
				'default'	=> 2,
			],
			[ // single_specialty_tablet_gap
				'id'		=> 'single_specialty_tablet_gap',
				'type'		=> 'spinner',
				'title'		=> esc_html__( "Tablet gap (px)", 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), '24' ),
				'min'		=> 1,
				'max'		=> 64,
				'default'	=> 16,
			],
			[ // single_specialty_mobile_cols
				'id'		=> 'single_specialty_mobile_cols',
				'type'		=> 'spinner',
				'title'		=> esc_html__( "Mobile columns", 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), '1' ),
				'min'		=> 1,
				'max'		=> 6,
				'default'	=> 1,
			],
			[ // single_specialty_mobile_gap
				'id'		=> 'single_specialty_mobile_gap',
				'type'		=> 'spinner',
				'title'		=> esc_html__( "Mobile gap (px)", 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), '24' ),
				'min'		=> 1,
				'max'		=> 64,
				'default'	=> 16,
			],
			[ // single_specialty_card_type
				'id'		=> 'single_specialty_card_type',
				'type'		=> 'image_select',
				'title'		=> esc_html__( "Specialists display type", 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), esc_html__( "Card 2", 'drplus' ) ),
				'options'	=> [
					'card-1'	=> [
						'alt'	=> esc_html__( "Card 1", 'drplus' ),
						'img'	=> DRPLUS_URI . "assets/images/backend/specialist-card-1.jpg",
						'title'	=> esc_html__( "Card 1", 'drplus' ),
					],
					'card-2'	=> [
						'alt'	=> esc_html__( "Card 2", 'drplus' ),
						'img'	=> DRPLUS_URI . "assets/images/backend/specialist-card-2.jpg",
						'title'	=> esc_html__( "Card 2", 'drplus' ),
					],
					'list'	=> [
						'alt'	=> esc_html__( "List", 'drplus' ),
						'img'	=> DRPLUS_URI . "assets/images/backend/specialist-list.jpg",
						'title'	=> esc_html__( "List", 'drplus' ),
					],
				],
				'default'	=> 'card-2',
			],
			[ // single_specialty_verified_text
				'id'			=> 'single_specialty_verified_text',
				'type'			=> 'text',
				'title'			=> esc_html__( 'Verified text', 'drplus' ),
				'desc'			=> esc_html__( 'If you leave it empty, the verified badge will not be shown.', 'drplus' ),
				'subtitle'		=> sprintf( __( "Default: %s", 'drplus' ), sprintf( esc_html__( 'Verified by %s', 'drplus' ), get_bloginfo( 'name' ) ) ),
				'default'		=> sprintf( esc_html__( 'Verified by %s', 'drplus' ), get_bloginfo( 'name' ) ),
				'placeholder'	=> sprintf( esc_html__( 'Verified by %s', 'drplus' ), get_bloginfo( 'name' ) ),
			],
			[ // single_specialty_page_description
				'id'		=> 'single_specialty_page_description',
				'type'		=> 'radio',
				'title'		=> esc_html__( 'Page description position', 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), esc_html__( 'Top', 'drplus' ) ),
				'data'		=> [
					'top'		=> esc_html__( 'Top', 'drplus' ),
					'bottom'	=> esc_html__( 'Bottom', 'drplus' ),
				],
				'default'	=> 'top',
			],
		),
	)
);
Redux::set_section( // Archives settings
	$opt_name,
	array(
		'title'			=> esc_html__( 'Specialities archive settings', 'drplus' ),
		'id'			=> 'specialities-archive-section',
		'subsection'	=> true,
		'fields'		=> array(
			[ // archive_specialities_breadcrumb
				'id'		=> 'archive_specialities_breadcrumb',
				'type'		=> 'switch',
				'title'		=> esc_html__( 'Show breadcrumb', 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), esc_html__( 'Enabled', 'drplus' ) ),
				'on'		=> esc_html__( 'Enabled', 'drplus' ),
				'off'		=> esc_html__( 'Disabled', 'drplus' ),
				'default'	=> true,
			],
			[ // archive_specialities_show_title
				'id'		=> 'archive_specialities_show_title',
				'type'		=> 'switch',
				'title'		=> esc_html__( 'Show archive title', 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), esc_html__( 'Enabled', 'drplus' ) ),
				'on'		=> esc_html__( 'Enabled', 'drplus' ),
				'off'		=> esc_html__( 'Disabled', 'drplus' ),
				'default'	=> true,
			],
			[ // archive_specialities_title_icon
				'id'			=> 'archive_specialities_title_icon',
				'type'			=> 'icon_select',
				'title'			=> esc_html__( 'Archive title icon', 'drplus' ),
				'compiler'		=> true,
				'default'		=> 'drplus-icon-stethoscope',
				'enqueue_frontend'	=> false,
				'stylesheet'	=> [
					[
						'url'		=> DRPLUS_URI . 'assets/css/iconly.min.css',
						'title'		=> __( 'Doctor plus icons', 'drplus' ),
						'prefix'	=> 'drplus-icon',
					],
				],
				'required'		=> [
					['archive_specialities_show_title','=',true]
				]
			],
			[ // archive_specialities_show_sidebar
				'id'		=> 'archive_specialities_show_sidebar',
				'type'		=> 'switch',
				'title'		=> esc_html__( 'Show archive sidebar', 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), esc_html__( 'Enabled', 'drplus' ) ),
				'on'		=> esc_html__( 'Enabled', 'drplus' ),
				'off'		=> esc_html__( 'Disabled', 'drplus' ),
				'default'	=> true,
			],
			[ // archive_specialities_sidebar
				'id'		=> 'archive_specialities_sidebar',
				'type'		=> 'select',
				'title'		=> esc_html__( 'Archive sidebar', 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), esc_html__( 'Archive Specialities', 'drplus' ) ),
				'data'		=> 'sidebars',
				'default'	=> 'archive_specialities',
				'required'	=> [
					['archive_specialities_show_sidebar','=',true],
				]
			],
			[ // archive_specialities_desktop_cols
				'id'		=> 'archive_specialities_desktop_cols',
				'type'		=> 'spinner',
				'title'		=> esc_html__( "Desktop columns", 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), '4' ),
				'min'		=> 1,
				'max'		=> 6,
				'default'	=> 4,
			],
			[ // archive_specialities_desktop_gap
				'id'		=> 'archive_specialities_desktop_gap',
				'type'		=> 'spinner',
				'title'		=> esc_html__( "Desktop gap (px)", 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), '24' ),
				'min'		=> 1,
				'max'		=> 64,
				'default'	=> 24,
			],
			[ // archive_specialities_tablet_cols
				'id'		=> 'archive_specialities_tablet_cols',
				'type'		=> 'spinner',
				'title'		=> esc_html__( "Tablet columns", 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), '3' ),
				'min'		=> 1,
				'max'		=> 6,
				'default'	=> 3,
			],
			[ // archive_specialities_tablet_gap
				'id'		=> 'archive_specialities_tablet_gap',
				'type'		=> 'spinner',
				'title'		=> esc_html__( "Tablet gap (px)", 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), '24' ),
				'min'		=> 1,
				'max'		=> 64,
				'default'	=> 16,
			],
			[ // archive_specialities_mobile_cols
				'id'		=> 'archive_specialities_mobile_cols',
				'type'		=> 'spinner',
				'title'		=> esc_html__( "Mobile columns", 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), '2' ),
				'min'		=> 1,
				'max'		=> 6,
				'default'	=> 2,
			],
			[ // archive_specialities_mobile_gap
				'id'		=> 'archive_specialities_mobile_gap',
				'type'		=> 'spinner',
				'title'		=> esc_html__( "Mobile gap (px)", 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), '24' ),
				'min'		=> 1,
				'max'		=> 64,
				'default'	=> 16,
			],
			[ // archive_specialities_show_speciality_icon
				'id'		=> 'archive_specialities_show_speciality_icon',
				'type'		=> 'switch',
				'title'		=> esc_html__( 'Show Speciality icon', 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), esc_html__( 'Enabled', 'drplus' ) ),
				'on'		=> esc_html__( 'Enabled', 'drplus' ),
				'off'		=> esc_html__( 'Disabled', 'drplus' ),
				'default'	=> true,
			],
			[ // archive_specialities_show_specialists_count
				'id'		=> 'archive_specialities_show_specialists_count',
				'type'		=> 'switch',
				'title'		=> esc_html__( 'Show specialists count', 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), esc_html__( 'Enabled', 'drplus' ) ),
				'on'		=> esc_html__( 'Enabled', 'drplus' ),
				'off'		=> esc_html__( 'Disabled', 'drplus' ),
				'default'	=> true,
			],
			[ // archive_specialities_show_specialists_arrow
				'id'		=> 'archive_specialities_show_specialists_arrow',
				'type'		=> 'switch',
				'title'		=> esc_html__( 'Show Speciality cart arrow', 'drplus' ),
				'subtitle'	=> sprintf( esc_html__( 'Default: %s', 'drplus' ), esc_html__( 'Enabled', 'drplus' ) ),
				'on'		=> esc_html__( 'Enabled', 'drplus' ),
				'off'		=> esc_html__( 'Disabled', 'drplus' ),
				'default'	=> true,
			],
		),
	)
);